resources:
  - ../../base
patchesStrategicMerge: 
  - ServiceMonitor.yaml

patches:
  - target:
      kind: Deployment
      name: prometheus
    patch: |-
      - op: add
        path: /metadata/namespace
        value: grafana
  - target:
      kind: Service
      name: prometheus
    patch: |-
      - op: add
        path: /metadata/namespace
        value: grafana
