resources:
  - ../../base

  

patches:
  - path: ServiceMonitor.yaml
    target:
      kind: ServiceMonitor
      name: backend-app-monitor
      namespace: grafana
  - target:
      kind: Deployment
      name: prometheus
    patch: |-
      - op: add
        path: /metadata/namespace
        value: grafana
  - target:
      kind: Service
      name: prometheus
    patch: |-
      - op: add
        path: /metadata/namespace
        value: grafana
