apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-app-monitor
  namespace: grafana
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
    - backend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
