resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: grafana
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: grafana
    patch: |
      - op: add
        path: /metadata/namespace 
        value: grafana
  - target:
      kind: Service
      name: grafana
    patch: |
      - op: add
        path: /metadata/namespace
        value: grafana
  - target:
      kind: ConfigMap
      name: grafana
    patch: |
      - op: add
        path: /metadata/namespace
        value: grafana
